/** NOVAÉ Sessiz Atelier: filtre omurgası solda, değişken ama okunaklı ürün ritmi sağda. */
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { ProductCard } from "@/components/ProductCard";
import { Category, products } from "@/data/products";

const categories: Category[] = ["Clothing","Shoes","Accessories"];
const colors = ["Black","White","Beige","Gray","Brown"];
const priceRanges = [{label:"€50 altı", min:0,max:50},{label:"€50–€100",min:50,max:100},{label:"€100–€200",min:100,max:200},{label:"€200+",min:200,max:Infinity}];

export default function Shop() {
  const queryParams = new URLSearchParams(window.location.search); const initialCategory = queryParams.get("category") as Category|null;
  const [search,setSearch]=useState(""); const [category,setCategory]=useState<Category|"All">(initialCategory&&categories.includes(initialCategory)?initialCategory:"All"); const [color,setColor]=useState("All"); const [size,setSize]=useState("All"); const [price,setPrice]=useState("All"); const [stock,setStock]=useState("All"); const [sort,setSort]=useState(queryParams.get("sort")||"featured"); const [mobileFilters,setMobileFilters]=useState(false);
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); if(params.get("category")) setCategory(params.get("category") as Category); if(params.get("sort")) setSort(params.get("sort")!); },[]);
  const listed = useMemo(()=>products.filter(p=>{const text=`${p.name} ${p.category} ${p.description} ${p.tags.join(" ")}`.toLocaleLowerCase("tr"); const range=priceRanges.find(r=>r.label===price); return text.includes(search.toLocaleLowerCase("tr"))&&(category==="All"||p.category===category)&&(color==="All"||p.colors.includes(color))&&(size==="All"||p.sizes.includes(size))&&(!range||(p.price>=range.min&&p.price<(range.max)))&&(stock==="All"||(stock==="In Stock"?p.stock:!p.stock)); }).sort((a,b)=>sort==="newest"?(Number(!!b.new)-Number(!!a.new))||b.id.localeCompare(a.id):sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="rating"?b.rating-a.rating:(Number(!!b.best)-Number(!!a.best))||b.rating-a.rating),[search,category,color,size,price,stock,sort]);
  const clear=()=>{setSearch("");setCategory("All");setColor("All");setSize("All");setPrice("All");setStock("All");}; const active= [category,color,size,price,stock].filter(v=>v!=="All").length;
  return <div className="container py-12 md:py-16"><div className="border-y border-stone-300 py-2"><div className="border-y border-stone-300/70 py-7"><p className="eyebrow">NOVAÉ / Koleksiyon — Sezon 01 / 2026</p><div className="mt-2 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h1 className="text-6xl leading-none md:text-7xl">Tüm <i>ürünler.</i></h1><p className="mt-4 text-sm text-stone-600">{listed.length} dikkatle seçilmiş parça.</p></div><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Parça, kategori ya da his ara" className="h-12 w-full border border-stone-300 bg-transparent pl-10 pr-4 text-sm outline-none transition focus:border-stone-800"/></div></div></div></div>
    <div className="mt-7 flex items-center justify-between gap-3 md:hidden"><button className="outline-button flex-1" onClick={()=>setMobileFilters(true)}><Filter size={15}/> Filtrele {active>0&&`(${active})`}</button><Sort value={sort} onChange={setSort}/></div>
    <div className="mt-8 grid gap-10 lg:grid-cols-[220px_1fr]"><aside className="hidden lg:block"><div className="sticky top-28"><div className="flex items-center justify-between border-y border-stone-300 py-1"><div className="flex-1 border-y border-stone-300/70 py-3"><p className="eyebrow">Filtreler / N</p></div>{active>0&&<button onClick={clear} className="text-[10px] font-bold tracking-[.12em] text-stone-500 uppercase hover:text-stone-900">Temizle</button>}</div><FilterBlock title="Kategori">{categories.map(c=><Choice key={c} label={c==="Clothing"?"Giyim":c==="Shoes"?"Ayakkabı":"Aksesuar"} selected={category===c} onClick={()=>setCategory(category===c?"All":c)}/>)}</FilterBlock><FilterBlock title="Fiyat">{priceRanges.map(r=><Choice key={r.label} label={r.label} selected={price===r.label} onClick={()=>setPrice(price===r.label?"All":r.label)}/>)}</FilterBlock><FilterBlock title="Renk">{colors.map(c=><Choice key={c} label={c} selected={color===c} onClick={()=>setColor(color===c?"All":c)}/>)}</FilterBlock><FilterBlock title="Beden">{["XS","S","M","L","XL"].map(s=><Choice key={s} label={s} selected={size===s} onClick={()=>setSize(size===s?"All":s)}/>)}</FilterBlock><FilterBlock title="Uygunluk"><Choice label="Stokta" selected={stock==="In Stock"} onClick={()=>setStock(stock==="In Stock"?"All":"In Stock")}/><Choice label="Tükendi" selected={stock==="Out of Stock"} onClick={()=>setStock(stock==="Out of Stock"?"All":"Out of Stock")}/></FilterBlock></div></aside><div><div className="hidden items-center justify-between border-y border-stone-300 py-1 lg:flex"><div className="flex-1 border-y border-stone-300/70 py-3"><p className="text-xs text-stone-500">{search?`“${search}” için sonuçlar`:"Sezonun tüm parçaları · N/01"}</p></div><div className="ml-4 flex items-center gap-2"><SlidersHorizontal size={15} className="text-[#849486]"/><Sort value={sort} onChange={setSort}/></div></div>{listed.length?<div className="mt-0 grid grid-cols-2 gap-x-4 gap-y-12 md:mt-8 md:grid-cols-3 md:gap-x-6">{listed.map((p,i)=><div key={p.id} className={i===3||i===10?"md:col-span-2 md:max-w-[calc(50%-.75rem)]":""}>{(i===3||i===10)&&<p className="eyebrow mb-3 border-t border-stone-300 pt-3">Edit {i===3?"A":"B"} / Material study</p>}<ProductCard product={p} priority={i<3}/></div>)}</div>:<div className="grid min-h-[440px] place-items-center border-t border-stone-300 text-center lg:mt-8"><div><Search className="mx-auto text-[#849486]" size={28}/><h2 className="mt-5 text-4xl">Burada bir eşleşme yok.</h2><p className="mt-3 text-sm text-stone-500">Aramanızı ya da seçtiğiniz filtreleri değiştirmeyi deneyin.</p><button className="quiet-button mt-6" onClick={clear}>Tüm filtreleri temizle</button></div></div>}</div></div>
    {mobileFilters&&<div className="fixed inset-0 z-[60] bg-[#22211f]/35" onClick={()=>setMobileFilters(false)}><section className="absolute inset-x-0 bottom-0 max-h-[82vh] overflow-y-auto bg-[#faf8f2] p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b pb-4"><div><p className="eyebrow">Koleksiyonu daraltın</p><h2 className="text-3xl">Filtreler</h2></div><button onClick={()=>setMobileFilters(false)} aria-label="Filtreleri kapat"><X/></button></div><div className="grid grid-cols-2 gap-x-7"><FilterBlock title="Kategori">{categories.map(c=><Choice key={c} label={c==="Clothing"?"Giyim":c==="Shoes"?"Ayakkabı":"Aksesuar"} selected={category===c} onClick={()=>setCategory(category===c?"All":c)}/>)}</FilterBlock><FilterBlock title="Fiyat">{priceRanges.map(r=><Choice key={r.label} label={r.label} selected={price===r.label} onClick={()=>setPrice(price===r.label?"All":r.label)}/>)}</FilterBlock><FilterBlock title="Renk">{colors.map(c=><Choice key={c} label={c} selected={color===c} onClick={()=>setColor(color===c?"All":c)}/>)}</FilterBlock><FilterBlock title="Beden">{["XS","S","M","L","XL"].map(s=><Choice key={s} label={s} selected={size===s} onClick={()=>setSize(size===s?"All":s)}/>)}</FilterBlock></div><div className="sticky bottom-0 -mx-5 mt-2 flex gap-2 bg-[#faf8f2] px-5 pt-4"><button className="outline-button flex-1" onClick={clear}>Temizle</button><button className="quiet-button flex-1" onClick={()=>setMobileFilters(false)}>Sonuçları gör ({listed.length})</button></div></section></div>}
  </div>;
}
function FilterBlock({title,children}:{title:string;children:React.ReactNode}){return <div className="border-b border-stone-300 py-5"><p className="mb-3 text-[11px] font-bold tracking-[.13em] uppercase">{title}</p><div className="space-y-2.5">{children}</div></div>}
function Choice({label,selected,onClick}:{label:string;selected:boolean;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-2 text-left text-xs text-stone-600 hover:text-stone-900"><span className={`grid h-4 w-4 place-items-center border ${selected?"border-[#849486] bg-[#849486]":"border-stone-400"}`}>{selected&&<span className="h-1.5 w-1.5 rounded-full bg-white"/>}</span>{label}</button>}
function Sort({value,onChange}:{value:string;onChange:(value:string)=>void}){return <div className="relative"><select value={value} onChange={e=>onChange(e.target.value)} className="appearance-none bg-transparent py-2 pl-2 pr-7 text-xs font-bold tracking-[.08em] outline-none"><option value="featured">Öne çıkanlar</option><option value="newest">En yeni</option><option value="low">Fiyat: düşükten yükseğe</option><option value="high">Fiyat: yüksekten düşüğe</option><option value="rating">En yüksek puan</option></select><ChevronDown className="pointer-events-none absolute right-0 top-1/2 -translate-y-1/2" size={15}/></div>}
