/** NOVAÉ Sessiz Atelier: ürün, bilgi bandı ve hızlı görünüm aynı kartta sakin biçimde birleşir. */
import { useState } from "react";
import { ArrowRight, Heart, ShoppingBag, Star, X } from "lucide-react";
import { Link } from "wouter";
import { Product, euro } from "@/data/products";
import { useStore } from "@/contexts/StoreContext";
import { toast } from "sonner";

export function ProductCard({ product, priority = false }: { product: Product; priority?: boolean }) {
  const { favorites, toggleFavorite, addToCart } = useStore();
  const [quick, setQuick] = useState(false);
  const favorite = favorites.includes(product.id);
  const quickAdd = () => { addToCart(product); toast.success("Sepete ayrıldı", { description: product.name }); };
  return <article className="group relative min-w-0 reveal">
    <div className="product-image relative aspect-[.78] overflow-hidden bg-stone-200"><Link href={`/product/${product.id}`} aria-label={product.name}><img src={product.image} alt={product.name} className="primary absolute inset-0 h-full w-full object-cover transition duration-500" loading={priority ? "eager" : "lazy"}/><img src={product.secondaryImage} alt="" className="secondary h-full w-full object-cover transition duration-500" loading="lazy"/></Link>{product.new&&<span className="absolute left-3 top-3 bg-[#faf8f2]/95 px-2 py-1 text-[9px] font-bold tracking-[.15em] uppercase">Yeni</span>}<button className={`absolute right-3 top-3 grid h-8 w-8 place-items-center bg-[#faf8f2]/95 transition hover:bg-[#faf8f2] ${favorite?"text-[#849486]":"text-stone-800"}`} onClick={()=>toggleFavorite(product.id)} aria-label={favorite?"Favorilerden kaldır":"Favorilere ekle"}><Heart size={16} fill={favorite?"currentColor":"none"}/></button><div className="absolute inset-x-3 bottom-3 flex translate-y-2 gap-2 opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100"><button onClick={()=>setQuick(true)} className="flex-1 bg-[#faf8f2]/95 px-2 py-3 text-[10px] font-bold tracking-[.13em] uppercase backdrop-blur-sm">Hızlı görünüm</button><button onClick={quickAdd} className="grid w-10 place-items-center bg-[#22211f] text-[#faf8f2]" aria-label="Sepete ekle"><ShoppingBag size={15}/></button></div></div>
    <div className="flex gap-3 border-b border-stone-300/70 pb-3 pt-3"><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Link href={`/product/${product.id}`} className="text-[13px] font-bold leading-5 hover:underline">{product.name}</Link><span className="shrink-0 text-[13px] font-bold">{euro(product.price)}</span></div><div className="mt-1 flex items-center justify-between"><p className="text-[10px] tracking-[.11em] text-stone-500 uppercase">N° {product.id.slice(1)} · {product.category}</p><span className="flex items-center gap-1 text-[10px] text-stone-500"><Star size={11} fill="currentColor"/> {product.rating.toFixed(1)}</span></div></div></div>
    {quick&&<QuickView product={product} close={()=>setQuick(false)}/>}
  </article>;
}

function QuickView({product,close}:{product:Product;close:()=>void}) { const {addToCart,toggleFavorite,favorites}=useStore(); const [size,setSize]=useState(product.sizes[0]); const [color,setColor]=useState(product.colors[0]); const add=()=>{addToCart(product,size,color);toast.success("Sepete ayrıldı",{description:`${product.name} · ${color}, ${size}`});close();}; return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#22211f]/45 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true"><div className="relative grid max-h-[90vh] w-full max-w-4xl overflow-y-auto bg-[#faf8f2] md:grid-cols-2"><button onClick={close} className="absolute right-4 top-4 z-10 grid h-9 w-9 place-items-center bg-[#faf8f2]" aria-label="Hızlı görünümü kapat"><X size={18}/></button><img src={product.image} alt={product.name} className="h-[44vh] w-full object-cover md:h-full"/><div className="p-7 md:p-10"><p className="eyebrow">{product.category}</p><h2 className="mt-2 text-4xl leading-none">{product.name}</h2><div className="mt-4 flex items-center gap-3 text-sm"><span className="font-bold">{euro(product.price)}</span><span className="flex items-center gap-1 text-stone-500"><Star size={13} fill="currentColor"/> {product.rating} ({product.reviews})</span></div><p className="mt-6 text-sm leading-6 text-stone-600">{product.description}</p><p className="mt-7 text-[10px] font-bold tracking-[.14em] uppercase">Renk — {color}</p><div className="mt-2 flex flex-wrap gap-2">{product.colors.map(c=><button key={c} onClick={()=>setColor(c)} className={`border px-3 py-2 text-xs ${color===c?"border-stone-900 bg-stone-900 text-white":"border-stone-300"}`}>{c}</button>)}</div><p className="mt-5 text-[10px] font-bold tracking-[.14em] uppercase">Beden — {size}</p><div className="mt-2 flex flex-wrap gap-2">{product.sizes.map(s=><button key={s} onClick={()=>setSize(s)} className={`min-w-10 border px-3 py-2 text-xs ${size===s?"border-stone-900 bg-stone-900 text-white":"border-stone-300"}`}>{s}</button>)}</div><button onClick={add} className="quiet-button mt-8 w-full">Sepete ekle <ShoppingBag size={15}/></button><div className="mt-4 flex justify-between"><Link href={`/product/${product.id}`} className="editorial-link" onClick={close}>Tüm ayrıntılar <ArrowRight size={14}/></Link><button onClick={()=>toggleFavorite(product.id)} className="editorial-link"><Heart size={14} fill={favorites.includes(product.id)?"currentColor":"none"}/> Kaydet</button></div></div></div></div>; }
